version: '3.8'

services:
  fraud-api:
    build: .
    container_name: fraud-api-container
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app/app
      - ./model:/app/model
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - fraud-network

networks:
  fraud-network:
    driver: bridge
